const QUESTIONS = {
    'question-tom-tom-club': {
        "cmonsurrender": "(C\u2019mon) Surrender",
        "youdontstopwordyrappinghood": "(You Don\u2019t Stop) Wordy Rappinghood",
        "96tears": "96 Tears",
        "96tearstakemetotheriver": "96 Tears / Take Me to the River",
        "asabovesobelow": "As Above, So Below",
        "asabovesobelowtakemetotheriver": "As Above, So Below /Take Me to the River",
        "asthediscoballturns": "As the Disco Ball Turns",
        "atsababy": "Atsababy!",
        "bambootown": "Bamboo Town",
        "beautiful": "Beautiful",
        "boomingandzooming": "Booming and Zooming",
        "bornforlove": "Born for Love",
        "brokenpromises": "Broken Promises",
        "callofthewild": "Call of the Wild",
        "challengeofthelovewarriors": "Challenge of the Love Warriors",
        "christmasintheclub": "Christmas in the Club",
        "daddycomehome": "Daddy Come Home",
        "dangerousdub": "Dangerous Dub",
        "darksneakloveaction": "Dark Sneak Love Action",
        "devildoesyourdogbite": "Devil Does Your Dog Bite?",
        "dogsinthetrash": "Dogs in the Trash",
        "dontsayno": "Don\u2019t Say No",
        "downtownrockers": "Downtown Rockers",
        "dreambaby": "Dream Baby",
        "elephant": "Elephant",
        "femmefatale": "Femme Fatale",
        "flyin": "Flyin\u2019",
        "happinesscantbuymoney": "Happiness Can\u2019t Buy Money",
        "holywater": "Holy Water",
        "iconfess": "I Confess",
        "ilestne": "Il Est Ne",
        "ilestn\u00e9": "Il est n\u00e9",
        "innocentsexkiss": "Innocent Sex Kiss",
        "introtowordyrappinghood": "Intro to Wordy Rappinghood",
        "irresistiblepartydip": "Irresistible Party Dip",
        "kissmewhenigetback": "Kiss Me When I Get Back",
        "kissinantonio": "Kissin' Antonio",
        "lelephant": "L'Elephant",
        "lesbianbythelake": "Lesbian by the Lake",
        "lesbiansbythelake": "Lesbians by the Lake",
        "lettherebelove": "Let There Be Love",
        "littleeva": "Little Eva",
        "lorelei": "Lorelei",
        "lovetape": "Love Tape",
        "lovewave": "Love Wave",
        "lovetoloveyoubaby": "Love to Love You Baby",
        "lovetoloveyoubabyoriginal": "Love to love you baby - Original",
        "manwiththe4wayhips": "Man With the 4\u2010Way Hips",
        "manyriverstocross": "Many Rivers to Cross",
        "measureup": "Measure Up",
        "mightyteardrop": "Mighty Teardrop",
        "mymamatoldme": "My Mama Told Me",
        "nevertookapenny": "Never Took a Penny",
        "onononon": "On, On, On, On\u2026",
        "onthelineagain": "On the Line Again",
        "ononon": "On, On, On\u2026",
        "onlythestrongsurvive": "Only the Strong Survive",
        "pleasureoflove": "Pleasure of Love",
        "psychokiller": "Psycho Killer",
        "punklolita": "Punk Lolita",
        "sand": "Sand",
        "sayiam": "Say I Am",
        "shebelongstome": "She Belongs to Me",
        "shesdangerous": "She\u2019s Dangerous",
        "shesafreak": "She\u2019s a Freak",
        "shocktheworld": "Shock the World",
        "soulfire": "Soul Fire",
        "spooks": "Spooks",
        "suboceana": "Suboceana",
        "sunshineandecstasy": "Sunshine and Ecstasy",
        "superdreaming": "Superdreaming",
        "sweetstothesweet": "Sweets to the Sweet",
        "takemetotheriver": "Take Me to the River",
        "talkingpt1": "Talking, Pt. 1",
        "talkingpt2": "Talking, Pt. 2",
        "talkingpt3": "Talking, Pt. 3",
        "thecallofthewild": "The Call of the Wild",
        "themanwiththe4wayhips": "The Man With the 4\u2010Way Hips",
        "thisisafoxyworld": "This Is a Foxy World",
        "timetobounce": "Time to Bounce",
        "timetobouncedub": "Time to Bounce Dub",
        "tomtomclubnprmusictinydeskconcert": "Tom Tom Club: NPR Music Tiny Desk Concert",
        "tomtomtheme": "Tom Tom Theme",
        "undertheboardwalk": "Under the Boardwalk",
        "wawadance": "Wa Wa Dance",
        "whofeelinit": "Who Feelin\u2019 It",
        "whowantsanuglygirl": "Who Wants an Ugly Girl?",
        "wontgiveyouup": "Won't Give You Up",
        "wordyrappinghood": "Wordy Rappinghood",
        "yella": "Yella",
        "youmakemerockandroll": "You Make Me Rock and Roll",
        "yousexything": "You Sexy Thing"
    }
}
