const QUESTIONS = {
    'question-tom-tom-club': {
        "cmonsurrender": "(C\u2019mon) Surrender",
        "youdontstopwordyrappinghood": "(You Don\u2019t Stop) Wordy Rappinghood",
        "96tears": "96 Tears",
        "96tearstakemetotheriver": "96 Tears / Take Me to the River",
        "asabovesobelow": "As Above, So Below",
        "asabovesobelowtakemetotheriver": "As Above, So Below /Take Me to the River",
        "asthediscoballturns": "As the Disco Ball Turns",
        "atsababy": "Atsababy!",
        "bambootown": "Bamboo Town",
        "beautiful": "Beautiful",
        "boomingandzooming": "Booming and Zooming",
        "bornforlove": "Born for Love",
        "brokenpromises": "Broken Promises",
        "callofthewild": "Call of the Wild",
        "challengeofthelovewarriors": "Challenge of the Love Warriors",
        "christmasintheclub": "Christmas in the Club",
        "daddycomehome": "Daddy Come Home",
        "dangerousdub": "Dangerous Dub",
        "darksneakloveaction": "Dark Sneak Love Action",
        "devildoesyourdogbite": "Devil Does Your Dog Bite?",
        "dogsinthetrash": "Dogs in the Trash",
        "dontsayno": "Don\u2019t Say No",
        "downtownrockers": "Downtown Rockers",
        "dreambaby": "Dream Baby",
        "elephant": "Elephant",
        "femmefatale": "Femme Fatale",
        "flyin": "Flyin\u2019",
        "happinesscantbuymoney": "Happiness Can\u2019t Buy Money",
        "holywater": "Holy Water",
        "iconfess": "I Confess",
        "ilestne": "Il Est Ne",
        "ilestn\u00e9": "Il est n\u00e9",
        "innocentsexkiss": "Innocent Sex Kiss",
        "introtowordyrappinghood": "Intro to Wordy Rappinghood",
        "irresistiblepartydip": "Irresistible Party Dip",
        "kissmewhenigetback": "Kiss Me When I Get Back",
        "kissinantonio": "Kissin' Antonio",
        "lelephant": "L'Elephant",
        "lesbianbythelake": "Lesbian by the Lake",
        "lesbiansbythelake": "Lesbians by the Lake",
        "lettherebelove": "Let There Be Love",
        "littleeva": "Little Eva",
        "lorelei": "Lorelei",
        "lovetape": "Love Tape",
        "lovewave": "Love Wave",
        "lovetoloveyoubaby": "Love to Love You Baby",
        "lovetoloveyoubabyoriginal": "Love to love you baby - Original",
        "manwiththe4wayhips": "Man With the 4\u2010Way Hips",
        "manyriverstocross": "Many Rivers to Cross",
        "measureup": "Measure Up",
        "mightyteardrop": "Mighty Teardrop",
        "mymamatoldme": "My Mama Told Me",
        "nevertookapenny": "Never Took a Penny",
        "onononon": "On, On, On, On\u2026",
        "onthelineagain": "On the Line Again",
        "ononon": "On, On, On\u2026",
        "onlythestrongsurvive": "Only the Strong Survive",
        "pleasureoflove": "Pleasure of Love",
        "psychokiller": "Psycho Killer",
        "punklolita": "Punk Lolita",
        "sand": "Sand",
        "sayiam": "Say I Am",
        "shebelongstome": "She Belongs to Me",
        "shesdangerous": "She\u2019s Dangerous",
        "shesafreak": "She\u2019s a Freak",
        "shocktheworld": "Shock the World",
        "soulfire": "Soul Fire",
        "spooks": "Spooks",
        "suboceana": "Suboceana",
        "sunshineandecstasy": "Sunshine and Ecstasy",
        "superdreaming": "Superdreaming",
        "sweetstothesweet": "Sweets to the Sweet",
        "takemetotheriver": "Take Me to the River",
        "talkingpt1": "Talking, Pt. 1",
        "talkingpt2": "Talking, Pt. 2",
        "talkingpt3": "Talking, Pt. 3",
        "thecallofthewild": "The Call of the Wild",
        "themanwiththe4wayhips": "The Man With the 4\u2010Way Hips",
        "thisisafoxyworld": "This Is a Foxy World",
        "timetobounce": "Time to Bounce",
        "timetobouncedub": "Time to Bounce Dub",
        "tomtomclubnprmusictinydeskconcert": "Tom Tom Club: NPR Music Tiny Desk Concert",
        "tomtomtheme": "Tom Tom Theme",
        "undertheboardwalk": "Under the Boardwalk",
        "wawadance": "Wa Wa Dance",
        "whofeelinit": "Who Feelin\u2019 It",
        "whowantsanuglygirl": "Who Wants an Ugly Girl?",
        "wontgiveyouup": "Won't Give You Up",
        "wordyrappinghood": "Wordy Rappinghood",
        "yella": "Yella",
        "youmakemerockandroll": "You Make Me Rock and Roll",
        "yousexything": "You Sexy Thing"
    },
    'question-men-without-hats': {
        "1999": "1999",
        "2000lightyearsfromhome": "2000 Light Years from Home",
        "allintostars": "All Into Stars",
        "allwedo": "All We Do",
        "alltheyoungdudes": "All the Young Dudes",
        "alternative80s": "Alternative 80s",
        "antarctica": "Antarctica",
        "banthegame": "Ban the Game",
        "blowathighdough": "Blow At High Dough",
        "body": "Body",
        "brightsideofthesun": "Bright Side of the Sun",
        "christinasworld": "Christina's World",
        "closetothesun": "Close to the Sun",
        "cocoricci": "Cocoricci",
        "dancenomore": "Dance No More",
        "dancinginthemoonlight": "Dancing in the Moonlight",
        "devilcomeround": "Devil Come Round",
        "dreaming": "Dreaming",
        "dubbeam": "Dub Beam",
        "editionsofyou": "Editions of You",
        "eloisei": "Eloise & I",
        "eurotheme": "Eurotheme",
        "everybodyknows": "Everybody Knows",
        "everybodywantstoknow": "Everybody Wants to Know",
        "everybodyssellingsomething": "Everybody\u2019s Selling Something",
        "falldowngently": "Fall Down Gently",
        "folkofthe80s": "Folk of the 80\u2019s",
        "folkoftheeighties": "Folk of the Eighties",
        "freeways": "Freeways",
        "gravityismyenemy": "Gravity Is My Enemy",
        "harrycrews": "Harry Crews",
        "headabovewater": "Head Above Water",
        "heaven": "Heaven",
        "herecomethe90s": "Here Come the 90\u2019s",
        "heymen": "Hey Men",
        "heysuperstar": "Hey Superstar",
        "homeonthebeam": "Home on the Beam",
        "howdoesitfeel": "How Does It Feel?",
        "iamthewalrus": "I Am the Walrus",
        "igotthemessage": "I Got the Message",
        "iknowtheirname": "I Know Their Name",
        "ilike": "I Like",
        "isinglastnotfortears": "I Sing Last / Not for Tears",
        "ideasforwalls": "Ideas for Walls",
        "iftheworldshouldendtoday": "If the World Should End Today",
        "incalifornia": "In California",
        "inthisworld": "In This World",
        "inthe21stcentury": "In the 21st Century",
        "inthemeadow": "In the Meadow",
        "inthenameofangels": "In the Name of Angels",
        "intoeloise": "Into: Eloise",
        "iminlove": "I\u2019m in Love",
        "jennyworeblack": "Jenny Wore Black",
        "justanotherday": "Just Another Day",
        "kenbarbielove": "Kenbarbielove",
        "lavalsedeug\u00e9nie": "La Valse d\u2019Eug\u00e9nie",
        "lavalsedeugenie": "La Valse d\u2019Eug\u00e9nie",
        "lifeafterdiamondhead": "Life After Diamond Head",
        "liveandlearn": "Live and Learn",
        "livinginchina": "Living in China",
        "losemyway": "Lose My Way",
        "lostforever": "Lost Forever",
        "love": "Love",
        "loveintheageofwar": "Love in the Age of War",
        "lovesepihany": "Love's Epihany",
        "messiahsdieyoung": "Messiahs Die Young",
        "modernedancing": "Modern (E) Dancing",
        "moderndancing": "Modern Dancing",
        "moonbeam": "Moonbeam",
        "moonbeambeammeup": "Moonbeam Beam Me Up",
        "mothersopinion": "Mother\u2019s Opinion",
        "mylove": "My Love",
        "myownadvice": "My Own Advice",
        "nadine": "Nadine",
        "nancysroom": "Nancy\u2019s Room",
        "nationale7": "Nationale 7",
        "nodancing": "No Dancing",
        "nofriendsofmine": "No Friends of Mine",
        "osolemio": "O Sole Mio",
        "ontuesday": "On Tuesday",
        "ousontmesmen": "Ou Sont Mes Men",
        "popgoestheworld": "Pop Goes the World",
        "rhythmofyouth": "Rhythm of Youth",
        "roses": "Roses",
        "sos": "S.O.S.",
        "satelliteoflove": "Satellite of Love",
        "security": "Security",
        "sideways": "Sideways",
        "telepathy": "Telepathy",
        "theend": "The End",
        "thegirlwiththesiliconeyes": "The Girl With the Silicon Eyes",
        "thegreatonesremember": "The Great Ones Remember",
        "thehumanrace": "The Human Race",
        "thejeanniebeckerinterview": "The Jeannie Becker Interview",
        "thejourneybegins": "The Journey Begins",
        "theloveinsideyourheart": "The Love Inside Your Heart",
        "therealworld": "The Real World",
        "thevandergraafgenerationblues": "The Van Der Graaf Generation Blues",
        "themefromthesummerof72": "Theme From \u201cThe Summer of \u201972\u201d",
        "thingsinmylife": "Things in My Life",
        "thiswar": "This War",
        "todaytomorrowyesterday": "Today Tomorrow Yesterday",
        "tomorrowtoday": "Tomorrow Today",
        "treblinka": "Treblinka",
        "underneaththerainbow": "Underneath the Rainbow",
        "unsatisfaction": "Unsatisfaction",
        "utterspace": "Utter Space",
        "whendoesthelovebegin": "When Does the Love Begin?",
        "wheredotheboysgo": "Where Do the Boys Go?",
        "wherethewildgo": "Where the Wild Go",
        "youme": "You & Me",
        "yourbeautifulheart": "Your Beautiful Heart"
    },
    'question-twisted-sister': {
        "12daysofchristmas": "12 Days of Christmas",
        "30": "30",
        "7minutesinheaven": "7 Minutes in Heaven",
        "ajperotribute": "A.J. Pero Tribute",
        "anywayyouwantitiwannarock": "Any Way You Want It / I Wanna Rock",
        "badboys": "Bad Boys",
        "badboysofrocknroll": "Bad Boys of Rock' n' Roll",
        "bandintroductions": "Band Introductions",
        "bechrooltoyourscuel": "Be Chrool to Your Scuel",
        "believeinrocknroll": "Believe In Rock'N'Roll",
        "biggun": "Big Gun",
        "blastinfastloud": "Blastin\u2019 Fast & Loud",
        "bluesuedeshoeswholelottashakinggoinonrocknrollisheretostay": "Blue Suede Shoes / Whole Lotta Shaking Goin' On / Rock 'n' Roll Is Here to Stay",
        "borntobewild": "Born to Be Wild",
        "burnthehell": "Burn The Hell",
        "burninhell": "Burn in Hell",
        "callmyname": "Call My Name",
        "cantstandstill": "Can\u2019t Stand Still",
        "captainhowdy": "Captain Howdy",
        "cfllmyname": "Cfll My Name",
        "chinesehustle": "Chinese Hustle",
        "comeallyefaithful": "Come All Ye Faithful",
        "comeback": "Comeback",
        "comeoutandplay": "Come Out and Play",
        "cumonfeelthenoizewerenotgonnatakeit": "Cum on Feel the Noize / We're Not Gonna Take It",
        "dayoftherocker": "Day of the Rocker",
        "deathfromabove": "Death From Above",
        "deathrun": "Death Run",
        "deckthehalls": "Deck the Halls",
        "deesdedication": "Dee's Dedication",
        "deesrap": "Dee's rap",
        "destroyer": "Destroyer",
        "documentary": "Documentary",
        "dontletmedown": "Don\u2019t Let Me Down",
        "eddietrunkandmikepiazzaintro": "Eddie Trunk and Mike Piazza Intro",
        "feelappeal": "Feel Appeal",
        "feelthepower": "Feel the Power",
        "floatin": "Floatin'",
        "followme": "Follow Me",
        "fourbarrelheartoflove": "Four Barrel Heart of Love",
        "greatballsoffire": "Great Balls of Fire",
        "hardcore": "Hardcore",
        "haveyourselfamerrychristmas": "Have Yourself a Merry Christmas",
        "haveyourselfamerrylittlechristmas": "Have Yourself a Merry Little Christmas",
        "heavymetalchristmas": "Heavy Metal Christmas",
        "heroesarehardtofind": "Heroes are Hard to Find",
        "highsteppin": "High Steppin\u2019",
        "honeylookthreetimes": "Honey, Look Three Times",
        "horrorteriaacaptainhowdybstreetjustice": "Horror Teria: A. Captain Howdy / B. Street Justice",
        "horrorteriathebeginningcaptainhowdystreetjustice": "Horror-Teria (The Beginning): Captain Howdy / Street Justice",
        "horrorteriaacaptainhowdy": "Horror-Teria: a) Captain Howdy",
        "horrorteriabstreetjustice": "Horror-Teria: b) Street Justice",
        "hotlove": "Hot Love",
        "iam": "I Am",
        "iamimme": "I Am, I'm me",
        "ibelieveinrocknroll": "I Believe in Rock \u2019n\u2019 Roll",
        "ibelieveinyou": "I Believe in You",
        "isawmommykissingsantaclaus": "I Saw Mommy Kissing Santa Claus",
        "iwannarock": "I Wanna Rock",
        "iwantthisnight": "I Want This Night",
        "iwillwin": "I Will Win",
        "illbehomeforchristmas": "I\u2019ll Be Home for Christmas",
        "illnevergrowup": "I'll Never Grow Up",
        "illnevergrowupnow": "I\u2019ll Never Grow Up, Now!",
        "illnewergrowupnow": "I'll Newer Grow Up Now!",
        "ifthatswhatyouwant": "If That\u2019s What You Want",
        "itsonlyrocknroll": "It\u2019s Only Rock \u2019n\u2019 Roll",
        "illtakeyoualive": "I\u2019ll Take You Alive",
        "imnoteverybody": "I\u2019m Not Everybody",
        "imsohotforyou": "I\u2019m So Hot for You",
        "ivehadenough": "I\u2019ve Had Enough",
        "jjguitarsoloplasticmoney": "JJ Guitar Solo / Plastic Money",
        "jailhouserock": "Jailhouse Rock",
        "johnnybgoode": "Johnny B. Goode",
        "kmetradiospot": "KMET Radio Spot",
        "killorbekillkillorbekilled": "Kill Or Be Kill [Kill Or Be Killed]",
        "killorbekilled": "Kill or Be Killed",
        "kingofthefools": "King of the Fools",
        "knifeintheback": "Knife in the Back",
        "ladysboy": "Lady\u2019s Boy",
        "leaderofthepack": "Leader of the Pack",
        "letitsnowletitsnowletitsnow": "Let It Snow, Let It Snow, Let It Snow",
        "letthegoodtimesroll": "Let the Good Times Roll",
        "letthegoodtimesrollfeelsofine": "Let the Good Times Roll / Feel So Fine",
        "likeaknifeintheback": "Like a Knife in the Back",
        "longtallsally": "Long Tall Sally",
        "lookinoutfornumber1": "Lookin' Out for Number 1",
        "lookinoutfor1": "Lookin\u2019 Out for #1",
        "loveisforsuckers": "Love Is for Suckers",
        "maybellene": "Maybellene",
        "meandtheboys": "Me and the Boys",
        "neversaynever": "Never Say Never",
        "ohcomeallyefaithful": "Oh Come All Ye Faithful",
        "onebadhabit": "One Bad Habit",
        "onemanwoman": "One Man Woman",
        "ourvoicewillbeheard": "Our Voice Will Be Heard",
        "outonthestreets": "Out on the Streets",
        "paytheprice": "Pay the Price",
        "photogallery": "Photo Gallery",
        "plasticmoney": "Plastic Money",
        "primemotivator": "Prime Motivator",
        "ridetolovelivetoride": "Ride To Love,Live To Ride",
        "ridetolivelivetoride": "Ride to Live, Live to Ride",
        "rocknrollsaviors": "Rock \u2019n\u2019 Roll Saviors",
        "rocknrollsaviours80": "Rock 'n' Roll Saviours '80",
        "rockon": "Rock On",
        "rockyou": "Rock You",
        "rolloverbeethoven": "Roll Over Beethoven",
        "runforyourlife": "Run for Your Life",
        "smf": "S.M.F.",
        "shessofine": "She\u2019s So Fine",
        "shootemdown": "Shoot'em Down",
        "silverbells": "Silver Bells",
        "sinaftersin": "Sin After Sin",
        "sincity": "Sin City",
        "statutorydate": "Statutory Date",
        "stayhungary": "Stay Hungary",
        "stayhungry": "Stay Hungry",
        "streetjustice": "Street Justice",
        "tvwife": "T.V. Wife",
        "tearitloose": "Tear It Loose",
        "thebeast": "The Beast",
        "theblade": "The Blade",
        "thechristmassong": "The Christmas Song",
        "thefirestillburns": "The Fire Still Burns",
        "thefirststillburns": "The First Still Burns",
        "thekidsareback": "The Kids Are Back",
        "thepowerandtheglory": "The Power and the Glory",
        "theprice": "The Price",
        "thisfireinside": "This Fire Inside",
        "thisonesforyou": "This One\u2019s for You",
        "tonight": "Tonight",
        "trainkeptarollin": "Train Kept a Rollin'",
        "tuttifrutti": "Tutti Frutti",
        "undertheblade": "Under the Blade",
        "undertheblad": "Under the Blad",
        "wakeup": "Wake Up",
        "wewishyouatwistedchristmas": "We Wish You a Twisted Christmas",
        "weregonnamakeit": "We\u2019re Gonna Make It",
        "werecomingon": "We\u2019re Coming On",
        "whatyoudontknow": "What You Don\u2019t Know",
        "whatyoudontknowsurecanhurtyou": "What You Don\u2019t Know Sure Can Hurt You",
        "whatslovewithoutyou": "What\u2019s Love Without You",
        "whitechristmas": "White Christmas",
        "withoutyou": "Without You",
        "workinonyoubaby": "Workin\u2019 On You Baby",
        "yeahright": "Yeah Right!",
        "youareallthatineed": "You Are All That I Need",
        "youcantstoprocknroll": "You Can\u2019t Stop Rock \u2019n\u2019 Roll",
        "youcantstoprockandroll": "You Can't Stop Rock and Roll",
        "yougottofight": "You Got to Fight",
        "youknowicry": "You Know I Cry",
        "youwantwhatwegot": "You Want What We Got",
        "yourenotalone": "You\u2019re Not Alone"
    },
    'question-midnight-oil': {
        "whatssofunnyaboutpeaceloveandunderstanding": "What\u2019s So Funny About Peace, Love and Understanding",
        "whatssofunnyboutpeaceloveandunderstanding": "(What\u2019s So Funny \u2019Bout) Peace, Love, and Understanding",
        "andthebandplayedwaltzingmatilda": "...And the Band Played Waltzing Matilda",
        "21stcenturyhuman": "21st Century Human",
        "acrocodilecries": "A Crocodile Cries",
        "asunburntsky": "A Sunburnt Sky",
        "aafanddrumsofheaven": "AAF and Drums of Heaven",
        "advanceaustraliafair": "Advance Australia Fair",
        "advanceaustraliafairbirdman": "Advance Australia Fair / Birdman",
        "andthebandplayedwaltzingmatildawxrt": "And the Band Played Waltzing Matilda [WXRT]",
        "antarctica": "Antarctica",
        "arcticworld": "Arctic World",
        "armisticeday": "Armistice Day",
        "atthetimeofwriting": "At the Time of Writing",
        "backontheborderline": "Back on the Borderline",
        "bakerman": "Bakerman",
        "barestdegree": "Barest Degree",
        "basementflat": "Basement Flat",
        "bedlambridge": "Bedlam Bridge",
        "beenawaytoolong": "Been Away Too Long",
        "bellsandhornsinthebackofbeyond": "Bells and Horns in the Back of Beyond",
        "bestofbothworlds": "Best of Both Worlds",
        "blackfellawhitefella": "Blackfella/Whitefella",
        "blossomandblood": "Blossom and Blood",
        "blot": "Blot",
        "blueskymine": "Blue Sky Mine",
        "bravefaces": "Brave Faces",
        "bringonthechange": "Bring on the Change",
        "bullroarer": "Bullroarer",
        "burnie": "Burnie",
        "bustobondi": "Bus to Bondi",
        "bushfire": "Bushfire",
        "cantseereason": "Can\u2019t See Reason",
        "capricornia": "Capricornia",
        "capricorniainterviewsepk": "Capricornia Interviews - EPK",
        "cemeteryinmymind": "Cemetery in My Mind",
        "cemeteryinmymindtruebelieversblindversion": "Cemetery in My Mind [True Believers Blind version]",
        "changethedate": "Change the Date",
        "coldcoldchange": "Cold Cold Change",
        "comfortableplaceonthecouch": "Comfortable Place on the Couch",
        "commonground": "Common Ground",
        "concrete": "Concrete",
        "deadheart": "Dead Heart",
        "desertmandesertwoman": "Desert Man, Desert Woman",
        "devilfishshuffle": "Devilfish Shuffle",
        "doghead": "Doghead",
        "dontwannabetheone": "Don\u2019t Wanna Be the One",
        "dreamworld": "Dreamworld",
        "dreamword": "Dreamword",
        "dropintheocean": "Drop in the Ocean",
        "drumsofheaven": "Drums of Heaven",
        "dust": "Dust",
        "ebeat": "E\u2010Beat",
        "earthandsunandmoon": "Earth and Sun and Moon",
        "endcredits": "End Credits",
        "ensemble": "Ensemble",
        "eyecontact": "Eye Contact",
        "eyecontactpictures": "Eye Contact / Pictures",
        "farm": "Farm",
        "feedingfrenzy": "Feeding Frenzy",
        "firstnation": "First Nation",
        "forgottenyears": "Forgotten Years",
        "forgotternyears": "Forgottern Years",
        "frontierwhatfrontier": "Frontier... What Frontier?",
        "furtherdiscussion": "Further Discussion",
        "gadigalland": "Gadigal Land",
        "ghostoftheroadhouse": "Ghost of the Roadhouse",
        "glitchbabyglitch": "Glitch Baby Glitch",
        "goldenage": "Golden Age",
        "gravelrash": "Gravelrash",
        "gunbarrelhighway": "Gunbarrel Highway",
        "harrisburg": "Harrisburg",
        "headoverheels": "Head Over Heels",
        "heartisnowhere": "Heart Is Nowhere",
        "heavenandearth": "Heaven and Earth",
        "helpsmehelpsyou": "Helps Me Helps You",
        "hercules": "Hercules",
        "home": "Home",
        "iseeyou": "I See You",
        "imthecure": "I\u2019m the Cure",
        "ifnedkellywasking": "If Ned Kelly Was King",
        "intherain": "In the Rain",
        "inthevalley": "In the Valley",
        "instantkarma": "Instant Karma",
        "introduction": "Introduction",
        "isitnow": "Is It Now?",
        "jimmysharmansboxers": "Jimmy Sharman\u2019s Boxers",
        "kids": "Kids",
        "kingofthemountain": "King of the Mountain",
        "kingdomofflaunt": "Kingdom of Flaunt",
        "kissthatgirl": "Kiss That Girl",
        "knifesedge": "Knife\u2019s Edge",
        "knowyourproduct": "Know Your Product",
        "koalasprint": "Koala Sprint",
        "kolelemai": "Kolele Mai",
        "kosciusko": "Kosciusko",
        "kosciuszko": "Kosciuszko",
        "koscuisko": "Koscuisko",
        "land": "Land",
        "lastfrontier": "Last Frontier",
        "locomotivebreath": "Locomotive Breath",
        "lostatsea": "Lost at Sea",
        "lovelife": "Love Life",
        "lovesonsale": "Loves on Sale",
        "luckycountry": "Lucky Country",
        "luritjaway": "Luritja Way",
        "madmanpropaganda": "Madman Propaganda",
        "maralinga": "Maralinga",
        "minutestomidnight": "Minutes to Midnight",
        "mosquitomarch": "Mosquito March",
        "mountainsofburma": "Mountains of Burma",
        "mycountry": "My Country",
        "nakedflame": "Naked Flame",
        "nomansland": "No Man\u2019s Land",
        "noreaction": "No Reaction",
        "notimeforgames": "No Time for Games",
        "nobodyschild": "Nobody\u2019s Child",
        "nothinglostnothinggained": "Nothing Lost-Nothing Gained",
        "noworneverland": "Now or Neverland",
        "onsongwriting": "On Songwriting",
        "onecountry": "One Country",
        "onetoomanytimes": "One Too Many Times",
        "onlythestrong": "Only the Strong",
        "outbreakoflove": "Outbreak of Love",
        "outro": "Outro",
        "outsideworld": "Outside World",
        "pictures": "Pictures",
        "poetsslaves": "Poets & Slaves",
        "poetsandslaves": "Poets and Slaves",
        "powderworks": "Powderworks",
        "powerthepassion": "Power & The Passion",
        "powerandthepassion": "Power and the Passion",
        "profiteers": "Profiteers",
        "progress": "Progress",
        "pubwithnobeer": "Pub With No Beer",
        "putdownthatweapon": "Put Down That Weapon",
        "putdowntheweapon": "Put Down the Weapon",
        "quinellaholiday": "Quinella Holiday",
        "readaboutit": "Read About It",
        "readallaboutit": "Read All About It",
        "realthing": "Real Thing",
        "redindian": "Red Indian",
        "redneckwonderland": "Redneck Wonderland",
        "redneckwonderlandconcrete": "Redneck Wonderland / Concrete",
        "reef": "Reef",
        "renaissanceman": "Renaissance Man",
        "returntosender": "Return to Sender",
        "reveille": "Reveille",
        "risingseas": "Rising Seas",
        "riverrunsred": "River Runs Red",
        "runbynight": "Run by Night",
        "safetychainblues": "Safety Chain Blues",
        "sayyourprayers": "Say Your Prayers",
        "schwampymoose": "Schwampy Moose",
        "screaminblue": "Scream in Blue",
        "section5": "Section 5",
        "section5bustobondi": "Section 5 [Bus to Bondi]",
        "sectionfive": "Section Five",
        "seeingisbelieving": "Seeing Is Believing",
        "sellmysoul": "Sell My Soul",
        "shakersmovers": "Shakers & Movers",
        "shakersandmovers": "Shakers and Movers",
        "shipsoffreedom": "Ships of Freedom",
        "shipyardsofnewzealand": "Shipyards of New Zealand",
        "shortmemory": "Short Memory",
        "sinsofomission": "Sins of Omission",
        "sleep": "Sleep",
        "smaththewobbleboard": "Smath the Wobbleboard",
        "somebodystryingtotellmesomething": "Somebody\u2019s Trying to Tell Me Something",
        "someoneelsetoblame": "Someone Else to Blame",
        "sometimes": "Sometimes",
        "spiritoftheage": "Spirit of the Age",
        "stagerant": "Stage rant",
        "standinline": "Stand in Line",
        "starofhope": "Star of Hope",
        "starsofwarburton": "Stars of Warburton",
        "surfsuptonight": "Surf\u2019s Up Tonight",
        "surfingwithaspoon": "Surfing With a Spoon",
        "takemedowneasy": "Take Me Down Easy",
        "tarkine": "Tarkine",
        "tellmethetruth": "Tell Me the Truth",
        "terroraustralia": "Terror Australia",
        "thealbumtitle": "The Album Title",
        "theaudiencefromthearchivalouttakes": "The Audience: From the Archival Outtakes",
        "thebandplayedthelastmelody": "The Band Played the Last Melody",
        "thebarkadarlingriver": "The Barka-Darling River",
        "thedeadheart": "The Dead Heart",
        "thegreatgibberplain": "The Great Gibber Plain",
        "thelastofthediggers": "The Last of the Diggers",
        "therealthing": "The Real Thing",
        "theredneckwonderlandvideo": "The Redneck Wonderland [video]",
        "therestaurationofmo84": "The Restauration of MO84",
        "theriverrunsred": "The River Runs Red",
        "theatricaltrailer": "Theatrical Trailer",
        "timetoheal": "Time to Heal",
        "tinlegstinmines": "Tin Legs & Tin Mines",
        "tinlegsandtinmines": "Tin-Legs and Tin Mines",
        "totheendsoftheearth": "To the Ends of the Earth",
        "tonepoem": "Tone Poem",
        "toomuchsunshine": "Too Much Sunshine",
        "treaty": "Treaty",
        "truganini": "Truganini",
        "tuganini": "Tuganini",
        "usforces": "US Forces",
        "undertheoverpass": "Under the Overpass",
        "undercover": "Undercover",
        "underwater": "Underwater",
        "usedabused": "Used & Abused",
        "usedandabused": "Used and Abused",
        "warakurna": "Warakurna",
        "wearenotafraid": "We Are Not Afraid",
        "wegottagetoutofthisplace": "We Gotta Get Out of This Place",
        "weresist": "We Resist",
        "wealthisvirtue": "Wealth Is Virtue",
        "weddingcakeisland": "Wedding Cake Island",
        "wharfrat": "Wharf Rat",
        "whatgoeson": "What Goes On",
        "whatssofunnyaboutpeace": "What\u2019s So Funny About Peace",
        "whenthegeneralstalk": "When the Generals Talk",
        "whiteskinblackheart": "White Skin Black Heart",
        "whocanstandintheway": "Who Can Stand in the Way",
        "whoah": "Whoah",
        "windinmyhead": "Wind in My Head",
        "worldthatisee": "World That I See",
        "wreckeryroad": "Wreckery Road",
        "writtenintheheart": "Written in the Heart",
        "youmaynotbereleased": "You May Not Be Released"
    },
    'question-dead-or-alive': {
        "absolutelynothing": "Absolutely Nothing",
        "andthenimetu": "And Then I Met U",
        "anotherworld": "Another World",
        "anything": "Anything",
        "areuready2bheartbroken": "Are U Ready 2 B Heartbroken",
        "babydontsaygoodbye": "Baby, Don\u2019t Say Goodbye",
        "beats2long": "Beats 2 Long",
        "beengone2long": "Been Gone 2 Long",
        "bigdaddyoftherhythm": "Big Daddy of the Rhythm",
        "blockc": "Block C",
        "bluechristmas": "Blue Christmas",
        "bluechristmas2000": "Blue Christmas 2000",
        "brandnewlover": "Brand New Lover",
        "cakeandeatit": "Cake and Eat It",
        "candlesintherain": "Candles in the Rain",
        "comehome": "Come Home",
        "comehomewithmebaby": "Come Home With Me, Baby",
        "comeinside": "Come Inside",
        "comeonwithmebaby": "Come on With Me Baby",
        "couldntcareless": "Couldn't Care Less",
        "djhitthatbutton": "DJ Hit That Button",
        "differentdrum": "Different Drum",
        "doit": "Do It",
        "donttellme": "Don't Tell Me",
        "evenbetterthantherealthing": "Even Better Than the Real Thing",
        "extacy": "Extacy",
        "fantheflame": "Fan the Flame",
        "fartoohard": "Far Too Hard",
        "flowers": "Flowers",
        "fragilemegamix": "Fragile Megamix",
        "getoutofmyhouse": "Get Out of My House",
        "gettingiton": "Getting It On",
        "gildedsplinters": "Gilded Splinters",
        "girlssong": "Girl's Song",
        "giveitback": "Give It Back",
        "giveitbackthatloveismine": "Give It Back That Love Is Mine",
        "giveittome": "Give It to Me",
        "gone2long": "Gone 2 Long",
        "gonetoolong": "Gone Too Long",
        "hitrunlover": "Hit & Run Lover",
        "hitandrunlover": "Hit and Run Lover",
        "hookedonlove": "Hooked on Love",
        "hurtme": "Hurt Me",
        "icannotcarryon": "I Cannot Carry On",
        "idontcareaboutyourheart": "I Don\u2019t Care About Your Heart",
        "idontwannabeyourboyfriend": "I Don\u2019t Wanna Be Your Boyfriend",
        "iparalyze": "I Paralyze",
        "ipromisedmyself": "I Promised Myself",
        "iwannabeatoy": "I Wanna Be a Toy",
        "iwant2bwithu": "I Want 2 B with U",
        "iwantyou": "I Want You",
        "iwishyoulove": "I Wish You Love",
        "iddoanything": "I\u2019d Do Anything",
        "illsaveyouallmykisses": "I\u2019ll Save You All My Kisses",
        "imfalling": "I\u2019m Falling",
        "imastar": "I\u2019m a Star",
        "imonfire": "I'm on Fire",
        "intoodeep": "In Too Deep",
        "internationalthing": "International Thing",
        "isntitapity": "Isn't It a Pity?",
        "itsbeenalongtime": "It\u2019s Been a Long Time",
        "itsbeenhoursnow": "It\u2019s Been Hours Now",
        "justwhatialwayswanted": "Just What I Always Wanted",
        "keepthatbodystrong": "Keep That Body Strong",
        "lovecomebacktome": "Love Come Back to Me",
        "lovetoy": "Love Toy",
        "lovercomeback": "Lover Come Back",
        "lovercomebacktome": "Lover Come Back to Me",
        "luckyday": "Lucky Day",
        "mistycircles": "Misty Circles",
        "mycoloringbook": "My Coloring Book",
        "myforbiddenlover": "My Forbidden Lover",
        "myfunnyvalentine": "My Funny Valentine",
        "myheartgoesbang": "My Heart Goes Bang",
        "myheartgoesbangbang": "My Heart Goes Bang Bang",
        "mylovesontheline": "My Love\u2019s on the Line",
        "namegame": "Namegame",
        "nevermarryanicon": "Never Marry an Icon",
        "nowheretonowhere": "Nowhere to Nowhere",
        "nukelopatra": "Nukelopatra",
        "nukleopatra": "Nukleopatra",
        "numbereleven": "Number Eleven",
        "numbertwelve": "Number Twelve",
        "partiallynudemedley": "Partially Nude Medley",
        "picturethis": "Picture This",
        "poplife": "Pop Life",
        "poplive": "Pop Live",
        "rebelrebel": "Rebel Rebel",
        "ripitup": "Rip It Up",
        "runningwild": "Running Wild",
        "selfishside": "Selfish Side",
        "sendintheclowns": "Send in the Clowns",
        "sexdrive": "Sex Drive",
        "sitonit": "Sit on It",
        "sleepwithyou": "Sleep With You",
        "someofthat": "Some of That",
        "somethinginmyhouse": "Something in My House",
        "sonofagun": "Son of a Gun",
        "specialstar": "Special Star",
        "spendthenighttogether": "Spend the Night Together",
        "stopkickingmyheartaround": "Stop Kicking My Heart Around",
        "stormyweathers": "Stormy Weathers",
        "turnaroundcount2tenycobremix": "TURN AROUND COUNT 2 TEN <Y & Co. \"B\" REMIX>",
        "thatstheway": "That\u2019s the Way",
        "thatsthewayilikeit": "That\u2019s the Way I Like It",
        "theart": "The Art",
        "thepartiallynudemedley": "The Partially Nude Medley",
        "therightstuff": "The Right Stuff",
        "thestranger": "The Stranger",
        "theyouthquakemedley": "The Youthquake Medley",
        "thentherewasyou": "Then There Was You",
        "thentherewasyoucomeinside": "Then There Was You/Come Inside",
        "tonight": "Tonight....",
        "totalstranger": "Total Stranger",
        "turnaroundcount2ten": "Turn Around & Count 2 Ten",
        "turnaroundcountto10": "Turn Around & Count to 10",
        "turnaroundandcount2ten": "Turn Around and Count 2 Ten",
        "turnaroundandcount2ten2000": "Turn Around And Count 2 Ten 2000",
        "turnaroundandcount2teb": "Turn Around and Count 2 Teb",
        "turnaroundandcount2ten2000extendedversion": "Turn Around and Count 2 Ten (2000) [extended version]",
        "turnaroundandcount2tenbluechristmasyoursweetness": "Turn Around and Count 2 Ten / Blue Christmas / Your Sweetness",
        "turnaroundandcounttoten": "Turn Around and Count to Ten",
        "uweremeant4me": "U Were Meant 4 Me",
        "unhappybirthday": "Unhappy Birthday",
        "unhappybirthdayninjabillymix": "Unhappy Birthday [Ninja Billy Mix]",
        "vivisection": "Vivisection",
        "whathaveudone": "What Have U Done",
        "whatiwant": "What I Want",
        "whereisthelove": "Where Is the Love",
        "whirlpool": "Whirlpool",
        "whysitsohard": "Why\u2019s It So Hard",
        "willyoustilllovemetomorrow": "Will You Still Love Me Tomorrow",
        "wishyouwerehere": "Wish You Were Here",
        "youmakemewanna": "You Make Me Wanna",
        "youspinmyloneliness": "You Spin My Loneliness",
        "yoursweetness": "Your Sweetness",
        "yoursweetnessisyourweakness": "Your Sweetness Is Your Weakness",
        "youthquake": "Youthquake"
    },
    'question-madness': {
        "dontletthemcatchyoucrying": "(Don\u2019t Let Them) Catch You Crying",
        "heyyouonestepbeyond": "(Hey You) One Step Beyond",
        "waitingfortheghosttrain": "Waiting for the Ghost Train",
        "youcantkeepagoodthingdown": "(You) Can\u2019t Keep a Good Thing Down",
        "1978": "1978",
        "420": "4:20",
        "4am": "4am",
        "7dials": "7 Dials",
        "adayonthetown": "A Day on the Town",
        "atownwithnoname": "A Town With No Name",
        "actonesurroundedonallsides": "Act One: \u201cSurrounded on All Sides\u2026\u201d",
        "actthreethesituationdeteriorates": "Act Three: \u201cThe Situation Deteriorates\u2026\u201d",
        "acttwothedamselindistress": "Act Two: \u201cThe Damsel in Distress\u2026\u201d",
        "africa": "Africa",
        "ainttherain": "Ain\u2019t the Rain",
        "airplane": "Airplane",
        "alliknew": "All I Knew",
        "animalfarm": "Animal Farm",
        "anotherversionofme": "Another Version of Me",
        "areyoucoming": "Are You Coming",
        "auditionconcreteandclay": "Audition Concrete and Clay",
        "auditionthehardertheycome": "Audition the Harder They Come",
        "auditiontheprince": "Audition the Prince",
        "babyburglar": "Baby Burglar",
        "baggytrousers": "Baggy Trousers",
        "beatthebride": "Beat the Bride",
        "bedbreakfastman": "Bed & Breakfast Man",
        "bedandbreakfast": "Bed and Breakfast",
        "bedandbreakfastman": "Bed and Breakfast Man",
        "beforewewaswe": "Before We Was We",
        "beginners101": "Beginners 101",
        "behindthe8ball": "Behind the 8 Ball",
        "believeme": "Believe Me",
        "bennybullfrog": "Benny Bullfrog",
        "bennythebullfrog": "Benny the Bullfrog",
        "bigtimesister": "Big Time Sister",
        "bingo": "Bingo",
        "bittersweet": "Bittersweet",
        "blackblue": "Black & Blue",
        "blackandblue": "Black and Blue",
        "blackbird": "Blackbird",
        "bluebeast": "Blue Beast",
        "blueskinnedbeast": "Blue Skinned Beast",
        "brandnewbeat": "Brand New Beat",
        "bullingdonboys": "Bullingdon Boys",
        "burningtheboats": "Burning the Boats",
        "callme": "Call Me",
        "callingcards": "Calling Cards",
        "canisayiloveyou": "Can I Say I Love You",
        "canttouchusnow": "Can\u2019t Touch Us Now",
        "cardiacarrest": "Cardiac Arrest",
        "carolson45": "Carols on 45",
        "checkmatelaluna": "Check Mate La Luna",
        "chipmunksarego": "Chipmunks Are Go!",
        "circusfreaks": "Circus Freaks",
        "clerkenwellpolka": "Clerkenwell Polka",
        "closeescape": "Close Escape",
        "coldestday": "Coldest Day",
        "crying": "Crying",
        "cryingshame": "Crying Shame",
        "culturevulture": "Culture Vulture",
        "cestlavie": "C\u2019est la vie",
        "dltjingle": "DLT Jingle",
        "dangermanakahighwire": "Dangerman AKA High Wire",
        "dangermen": "Dangermen",
        "davidhamiltonjingle": "David Hamilton Jingle",
        "dayonthetown": "Day on the Town",
        "deathofarude": "Death of a Rude",
        "deathofarudeboy": "Death of a Rude Boy",
        "deceivestheeye": "Deceives the Eye",
        "deceivestheeyes": "Deceives the Eyes",
        "deolali": "Deolali",
        "disappear": "Disappear",
        "dispara": "Dispara",
        "doelali": "Doelali",
        "dontquotemeonthat": "Don\u2019t Quote Me on That",
        "dontleavethepastbehindyou": "Don\u2019t Leave the Past Behind You",
        "dontlookback": "Don\u2019t Look Back",
        "dreaderthandread": "Dreader Than Dread",
        "dreamingman": "Dreaming Man",
        "dripfedfred": "Drip Fed Fred",
        "drivinginmycar": "Driving in My Car",
        "duncanjohnstonejingle": "Duncan Johnstone Jingle",
        "dustdevil": "Dust Devil",
        "dustdevili": "Dust Devil I",
        "ernie": "E.R.N.I.E.",
        "elregressodelaspalmas7": "El Regresso De Las Palmas 7",
        "elregressodelospalmas7": "El Regresso de Los Palmas 7",
        "elysium": "Elysium",
        "embaressment": "Embaressment",
        "embarrasment": "Embarrasment",
        "embarrassment": "Embarrassment",
        "embarressment": "Embarressment",
        "epilogueandsoladiesandgentlemen": "Epilogue: \u201cAnd So Ladies and Gentlemen\u2026\u201d",
        "feelsofine": "Feel So Fine",
        "fightforyourright": "Fight for Your Right",
        "finladiesandgentlemen": "Fin.: \u201cLadies and Gentlemen\u2026\u201d",
        "fireballxl5": "Fireball XL5",
        "fishchips": "Fish & Chips",
        "fishchipsparade": "Fish & Chips Parade",
        "fishandchips": "Fish and Chips",
        "foreveryoung": "Forever Young",
        "fridaynightsaturdaymorning": "Friday Night, Saturday Morning",
        "fromanotherworld": "From Another World",
        "gabrielshorn": "Gabriel\u2019s Horn",
        "garytibbsjingle": "Gary Tibbs Jingle",
        "girlwhydontyou": "Girl Why Don\u2019t You?",
        "girlwhydontya": "Girl Why Don\u2019t Ya",
        "givemeareason": "Give Me a Reason",
        "giventheopportunity": "Given the Opportunity",
        "glastonburyfestival2009pyramidstage": "Glastonbury Festival 2009: Pyramid Stage",
        "goingtothetop": "Going to the Top",
        "goodman": "Good Man",
        "goodtimes": "Good Times",
        "goodbyemrchips": "Goodbye Mr Chips",
        "grandslam": "Grandslam",
        "greeneyes": "Green Eyes",
        "greyday": "Grey Day",
        "guns": "Guns",
        "happychristmasfromthestars": "Happy Christmas From the Stars",
        "hellosun": "Hello Sun",
        "herbert": "Herbert",
        "hondacity": "Honda City",
        "hourofneed": "Hour of Need",
        "houseoffun": "House of Fun",
        "howcanitellyou": "How Can I Tell You",
        "huffetypuff": "Huffety Puff",
        "hunchbackoftorriano": "Hunchback of Torriano",
        "ibelieve": "I Believe",
        "ichasethedevil": "I Chase the Devil",
        "ichasethedevilakaironshirt": "I Chase the Devil AKA Ironshirt",
        "ipronounceyou": "I Pronounce You",
        "iwastheone": "I Was the One",
        "illcompete": "I\u2019ll Compete",
        "idiotchild": "Idiot Child",
        "ifididntcare": "If I Didn't Care",
        "ifigomad": "If I Go Mad",
        "ifyouthinktheressomething": "If You Think There\u2019s Something",
        "inmystreet": "In My Street",
        "inthecity": "In the City",
        "inthehallofthemountainking": "In the Hall of the Mountain King",
        "inthemiddleofthenight": "In the Middle of the Night",
        "intherain": "In the Rain",
        "inanityoverchristmas": "Inanity Over Christmas",
        "intotheblue": "Into the Blue",
        "ironshirt": "Iron Shirt",
        "isthereanybodyoutthere": "Is There Anybody Out There?",
        "israelites": "Israelites",
        "itmustbelove": "It Must Be Love",
        "iddoanything": "I\u2019d Do Anything",
        "imsorry": "I\u2019m Sorry",
        "ivegotyou": "I\u2019ve Got You",
        "jennie": "Jennie",
        "johhnythehorse": "Johhny the Horse",
        "johnjones": "John Jones",
        "johnnythehorse": "Johnny the Horse",
        "keepmoving": "Keep Moving",
        "kidjensenjingle": "Kid Jensen Jingle",
        "kitchenfloor": "Kitchen Floor",
        "laluna": "La Luna",
        "landofhopeglory": "Land of Hope & Glory",
        "landofhopeandglory": "Land of Hope and Glory",
        "legrandpantalon": "Le Grand Pantalon",
        "leon": "Leon",
        "letsgo": "Let\u2019s Go",
        "lifeisagame": "Life Is a Game",
        "lightoftheway": "Light of the Way",
        "listentoyourfather": "Listen to Your Father",
        "lockdownandfrackoff": "Lockdown and Frack Off",
        "lola": "Lola",
        "longgoodbye": "Long Goodbye",
        "lostmyhead": "Lost My Head",
        "lovereallyhurts": "Love Really Hurts",
        "lovestruck": "Lovestruck",
        "mkii": "MKII",
        "mk2": "MK2",
        "madhouse": "Mad House",
        "madnotmad": "Mad Not Mad",
        "maddley": "Maddley",
        "madness": "Madness",
        "madnessisallinthemind": "Madness Is All in the Mind",
        "madnessmegamix": "Madness Megamix",
        "marchofthegherkins": "March of the Gherkins",
        "maybeinanotherlife": "Maybe in Another Life",
        "memories": "Memories",
        "michaelcaine": "Michael Caine",
        "michaelcane": "Michael Cane",
        "mikereidjingle": "Mike Reid Jingle",
        "mikesmithjingle": "Mike Smith Jingle",
        "misery": "Misery",
        "missingyou": "Missing You",
        "missionfromhell": "Mission From Hell",
        "mistakes": "Mistakes",
        "moneymoneymoney": "Money Money Money",
        "moondance": "Moondance",
        "mrspeaker": "Mr Speaker",
        "mrapples": "Mr. Apples",
        "mrshutchinson": "Mrs. Hutchinson",
        "mumbojumbo": "Mumbo Jumbo",
        "mummysboy": "Mummy\u2019s Boy",
        "mygirl": "My Girl",
        "mygirl2": "My Girl 2",
        "mygirllollipop": "My Girl Lollipop",
        "mymumsroses": "My Mums Roses",
        "myobsession": "My Obsession",
        "myoldman": "My Old Man",
        "nw5": "NW5",
        "naturalact": "Natural Act",
        "neverasktwice": "Never Ask Twice",
        "neverknewyourname": "Never Knew Your Name",
        "newdelhi": "New Delhi",
        "nickyhornjingle": "Nicky Horn Jingle",
        "nightboattocairo": "Nightboat to Cairo",
        "nightboattocario": "Night Boat to Cario",
        "nomoney": "No Money",
        "noreason": "No Reason",
        "nortonfolgate": "Norton Folgate",
        "nothometoday": "Not Home Today",
        "nuttysounds": "Nutty Sounds",
        "nuttytheme": "Nutty Theme",
        "ohmylove": "Oh My Love",
        "onthebeatpete": "On the Beat Pete",
        "onthetown": "On the Town",
        "onebetterday": "One Better Day",
        "onefineday": "One Fine Day",
        "onesecondsthoughtlessness": "One Second\u2019s Thoughtlessness",
        "onestepbeyond": "One Step Beyond\u2026",
        "overdone": "Overdone",
        "overture": "Overture",
        "pacamac": "Pac\u2010a\u2010Mac",
        "pamthehawk": "Pam the Hawk",
        "patience": "Patience",
        "perfectplace": "Perfect Place",
        "peterpowelljingle": "Peter Powell Jingle",
        "peteryoungjingle": "Peter Young Jingle",
        "petesbeat": "Pete\u2019s Beat",
        "pigbag": "Pigbag",
        "pleasedontgo": "Please Don\u2019t Go",
        "pleasereleaseme": "Please Release Me",
        "powderblue": "Powder Blue",
        "preciousone": "Precious One",
        "primrosehill": "Primrose Hill",
        "prologuemrbeckettsir": "Prologue: \u201cMr Beckett Sir\u2026\u201d",
        "promisespromises": "Promises, Promises",
        "prospects": "Prospects",
        "radio2liveinhydepark2016": "Radio 2 Live in Hyde Park 2016",
        "rain": "Rain",
        "rainbows": "Rainbows",
        "razorbladealley": "Razorblade Alley",
        "regresodelospalmas7": "Regreso de Los Palmas 7",
        "rehearsals": "Rehearsals",
        "releaseme": "Release Me",
        "releasemecloseescapesolidgone": "Release Me / Close Escape / Solid Gone",
        "returnofthelospalmas7": "Return of the Los Palmas 7",
        "ridingonmybike": "Riding on My Bike",
        "riseandfall": "Rise and Fall",
        "rockinina": "Rockin\u2019 in A\u266d",
        "rockinginaflat": "Rocking in A Flat",
        "rockininaflat": "Rockin\u2019 in a Flat",
        "rogerscottjingle": "Roger Scott Jingle",
        "roughkids": "Rough Kids",
        "roundwego": "Round We Go",
        "roundandround": "Round and Round",
        "rulesofdeolali": "Rules of Deolali",
        "runforyourlife": "Run for Your Life",
        "samantha": "Samantha",
        "sarah": "Sarah",
        "sarahssong": "Sarah\u2019s Song",
        "saturdaynightsundaymorning": "Saturday Night, Sunday Morning",
        "setmefree": "Set Me Free",
        "sevendials": "Seven Dials",
        "sevenyearscratch": "Seven Year Scratch",
        "sexanddrugsandrocknroll": "Sex and Drugs and Rock \u2019n\u2019 Roll",
        "shadowoffear": "Shadow of Fear",
        "shadowonthehouse": "Shadow on the House",
        "shamescandal": "Shame & Scandal",
        "shameandscandal": "Shame and Scandal",
        "shoparound": "Shoparound",
        "shutup": "Shut Up",
        "signofthetimes": "Sign of the Times",
        "simonbatesjingles": "Simon Bates Jingles",
        "simpleequation": "Simple Equation",
        "skylarking": "Skylarking",
        "smallworld": "Small World",
        "smashwaltz": "Smash Waltz",
        "soalive": "So Alive",
        "soalivefalsestart": "So Alive\u2026 False Start",
        "somuchtroubleintheworld": "So Much Trouble in the World",
        "solidgone": "Solid Gone",
        "sorry": "Sorry",
        "souldenying": "Soul Denying",
        "starvation": "Starvation",
        "steppingintoline": "Stepping Into Line",
        "sugarspice": "Sugar & Spice",
        "sugarandspice": "Sugar and Spice",
        "suggsbedderstrackbytrack": "Suggs & Bedders Track by Track",
        "summerpartymix": "Summer Party Mix",
        "suntherain": "Sun & the Rain",
        "sundaymorning": "Sunday Morning",
        "sunshinevoice": "Sunshine Voice",
        "swanlake": "Swan Lake",
        "sweetestgirl": "Sweetest Girl",
        "takeitorleaveit": "Take It or Leave It",
        "tallerthanyouare": "Taller Than You Are",
        "tarzansnuts": "Tarzan\u2019s Nuts",
        "tearsyoucanthide": "Tears You Can\u2019t Hide",
        "terrywoganjingle": "Terry Wogan Jingle",
        "thatclose": "That Close",
        "thatface": "That Face",
        "thatsthewaytodoit": "That\u2019s the Way to Do It",
        "thealligatorsong": "The Alligator Song",
        "thebedandbreakfastman": "The Bed and Breakfast Man",
        "thebusiness": "The Business",
        "thecommunicator": "The Communicator",
        "thehardertheycome": "The Harder They Come",
        "thekiss": "The Kiss",
        "thelastragandboneman": "The Last Rag and Bone Man",
        "thelawaccordingtodrkippah": "The Law According to Dr. Kippah",
        "thelibertyofnortonfolgate": "The Liberty of Norton Folgate",
        "thenationalanthem": "The National Anthem",
        "theopiumeaters": "The Opium Eaters",
        "theprince": "The Prince",
        "thereturnoflospalmas7": "The Return of Los Palmas 7",
        "thereturnofthelospalmas": "The Return of the Los Palmas",
        "thereturnofthelospalmas7": "The Return of the Los Palmas 7",
        "thereturnofthelospalmasseven": "The Return of the Los Palmas Seven",
        "theriseandfall": "The Rise and Fall",
        "theroadettesong": "The Roadette Song",
        "thesuntherain": "The Sun & the Rain",
        "thesunandtherain": "The Sun and the Rain",
        "thewizard": "The Wizard",
        "theyoungandtheold": "The Young and the Old",
        "theatreoftheabsurd": "Theatre of the Absurd",
        "thisiswhere": "This Is Where",
        "time": "Time",
        "timefortea": "Time for Tea",
        "tiptoes": "Tiptoes",
        "tomorrows": "Tomorrow\u2019s",
        "tomorrowsdream": "Tomorrow\u2019s Dream",
        "tomorrowsjustanotherday": "Tomorrow\u2019s Just Another Day",
        "tonyblackburnjingle": "Tony Blackburn Jingle",
        "track13": "Track13",
        "turningblue": "Turning Blue",
        "unpasoadelante": "Un paso adelante!",
        "unpasoavanti": "Un Paso Avanti",
        "unpassoavanti": "Un Passo Avanti",
        "unclesam": "Uncle Sam",
        "victoriagardens": "Victoria Gardens",
        "vietnam": "Vietnam",
        "visittodracsteincastle": "Visit to Dracstein Castle",
        "walkingwithmrwheeze": "Walking With Mr. Wheeze",
        "waltzintomischief": "Waltz Into Mischief",
        "wearelondon": "We Are London",
        "wearelove": "We Are Love",
        "wewantfreddie": "We Want Freddie",
        "whatonearthisit": "What on Earth Is It",
        "whatsthat": "What's That",
        "whendawnarrives": "When Dawn Arrives",
        "whistleinthedark": "Whistle in the Dark",
        "whiteheat": "White Heat",
        "wingsofadove": "Wings of a Dove",
        "winterinwonderland": "Winter in Wonderland",
        "yesterdaysmen": "Yesterday\u2019s Men",
        "yesterdaysman": "Yesterday\u2019s Man",
        "youaremyeverything": "You Are My Everything",
        "youkeepmehangingon": "You Keep Me Hanging On",
        "yousaid": "You Said",
        "yourewonderful": "You're Wonderful",
        "youllloseagoodthing": "You\u2019ll Lose a Good Thing",
        "younggunsdocumentary": "\u2018Young Guns\u2019 Documentary"
    },
    'question-the-buggles': {
        "adventuresinmodernrecording": "Adventures in Modern Recording",
        "andyouandi": "And You and I",
        "astroboy": "Astroboy",
        "beatnik": "Beatnik",
        "bluenylon": "Blue Nylon",
        "cleanclean": "Clean, Clean!",
        "dion": "Dion",
        "elstree": "Elstree",
        "fadeaway": "Fade Away",
        "gothroughthis": "Go Through This",
        "iamacamera": "I Am a Camera",
        "iloveyou": "I Love You",
        "innercity": "Inner City",
        "intothelens": "Into the Lens",
        "island": "Island",
        "johnnyonthemonorail": "Johnny on the Monorail",
        "kiddynamo": "Kid Dynamo",
        "lenny": "Lenny",
        "livingintheplasticage": "Living in the Plastic Age",
        "livinginaplasticage": "Living in a Plastic Age",
        "machinemessiah": "Machine Messiah",
        "ontv": "On TV",
        "polythenesymphonia": "Polythene Symphonia",
        "rainbowwarrior": "Rainbow Warrior",
        "ridingatide": "Riding a Tide",
        "roundabout": "Roundabout",
        "starshiptrooper": "Starship Trooper",
        "technopop": "Technopop",
        "tempusfugit": "Tempus Fugit",
        "theplasticage": "The Plastic Age",
        "vermilionsands": "Vermilion Sands",
        "videotheque": "Videotheque",
        "walkingonglass": "Walking on Glass",
        "wecanflyfromhere": "We Can Fly From Here",
        "youcanflyfromhere": "You Can Fly From Here"
    },
    "question-a-ha": {
        "9dream": "#9 Dream",
        "seeminglynonstopjuly": "(Seemingly) Nonstop July",
        "abreakintheclouds": "A Break in the Clouds",
        "afineblueline": "A Fine Blue Line",
        "alittlebit": "A Little Bit",
        "aquestionoflust": "A Question of Lust",
        "afternoonhigh": "Afternoon High",
        "alltheplanesthatcomeinonthequiet": "All the Planes That Come in on the Quiet",
        "analogue": "Analogue",
        "andyoutellme": "And You Tell Me",
        "angel": "Angel",
        "angelinthesnow": "Angel in the Snow",
        "asif": "As If",
        "barroom": "Bar Room",
        "barelyhangingon": "Barely Hanging On",
        "behindthescenes": "Behind the Scenes",
        "betweenyourmamaandyourself": "Between Your Mama and Yourself",
        "betweenthehaloandthehorn": "Between the Halo and the Horn",
        "birthright": "Birthright",
        "bluestofblue": "Bluest of Blue",
        "bumblebee": "Bumblebee",
        "butterflybutterfly": "Butterfly, Butterfly",
        "cannothide": "Cannot Hide",
        "caseclosedonsilvershore": "Case Closed on Silver Shore",
        "castinsteel": "Cast in Steel",
        "celice": "Celice",
        "celiceliveatfrognerparkenoslo": "Celice [Live at Frognerparken - Oslo]",
        "celicevideothomasschumacheredit": "Celice [Video - Thomas Schumacher edit]",
        "coldriver": "Cold River",
        "coldasstone": "Cold as Stone",
        "coldasstonesycamoreleaves": "Cold as Stone/Sycamore Leaves",
        "cosyprisons": "Cosy Prisons",
        "cosyprisonsliveatfrognerparkenoslo": "Cosy Prisons [Live at Frognerparken - Oslo]",
        "crywolf": "Cry Wolf",
        "cryingintherain": "Crying in the Rain",
        "darkisthenight": "Dark Is the Night",
        "darkisthenightforall": "Dark Is the Night for All",
        "daysonend": "Days on End",
        "didanyoneapproachyou": "Did Anyone Approach You?",
        "differences": "Differences",
        "documentary": "Documentary",
        "dontdomeanyfavours": "Don\u2019t Do Me Any Favours",
        "doorajar": "Door Ajar",
        "dotthei": "Dot the I",
        "dragonfly": "Dragonfly",
        "dreammyselfalive": "Dream Myself Alive",
        "driftwood": "Driftwood",
        "earlymorning": "Early Morning",
        "eastofthesun": "East of the Sun",
        "evitar": "Evitar",
        "footofthemountain": "Foot of the Mountain",
        "forestfire": "Forest Fire",
        "forestforthetrees": "Forest for the Trees",
        "forevernotyours": "Forever Not Yours",
        "givinguptheghost": "Giving Up the Ghost",
        "gotosleep": "Go to Sleep",
        "goodbyethompson": "Goodbye Thompson",
        "halfwaythroughthetour": "Halfway Through the Tour",
        "hereistandandfacetherain": "Here I Stand and Face the Rain",
        "holyground": "Holy Ground",
        "howsweetitwas": "How Sweet It Was",
        "hunterinthehills": "Hunter in the Hills",
        "huntinghighlow": "Hunting High & Low",
        "huntinghighandlow": "Hunting High and Low",
        "hurryhome": "Hurry Home",
        "icallyourname": "I Call Your Name",
        "idreammyselfalive": "I Dream Myself Alive",
        "iwishicared": "I Wish I Cared",
        "iwontforgether": "I Won\u2019t Forget Her",
        "ivebeenlosingyou": "I\u2019ve Been Losing You",
        "illneverfindstreetfulcity": "I\u2019ll Never Find Streetful City",
        "imin": "I\u2019m In",
        "ivebeenloosingyou": "I\u2019ve Been Loosing You",
        "ivebeenlosingyoucrywolf": "I\u2019ve Been Losing You / Cry Wolf",
        "keeperoftheflame": "Keeper of the Flame",
        "lambtotheslaughter": "Lamb to the Slaughter",
        "lessthanpure": "Less Than Pure",
        "lessonone": "Lesson One",
        "liedownindarkness": "Lie Down in Darkness",
        "liedownondarkness": "Lie Down on Darkness",
        "lifelines": "Lifelines",
        "lifesnotfair": "Life\u2019s Not Fair",
        "littleblackheart": "Little Black Heart",
        "livingaboysadventuretale": "Living a Boy\u2019s Adventure Tale",
        "livingattheendoftheworld": "Living at the End of the World",
        "llorandoenlalluvia": "Llorando en la lluvia",
        "locust": "Locust",
        "loveisreason": "Love Is Reason",
        "makeitsoon": "Make It Soon",
        "makemeunderstand": "Make Me Understand",
        "manhattanskyline": "Manhattan Skyline",
        "maryellenmakesthemomentcount": "Mary Ellen Makes the Moment Count",
        "maybemaybe": "Maybe, Maybe",
        "megamix": "Megamix",
        "memorialbeach": "Memorial Beach",
        "minorearthmajorsky": "Minor Earth, Major Sky",
        "minorkeysonata": "Minor Key Sonata",
        "mondaymourning": "Monday Mourning",
        "mothernaturegoestoheaven": "Mother Nature Goes to Heaven",
        "movetomemphis": "Move to Memphis",
        "mythomania": "Mythomania",
        "nevernever": "Never Never",
        "nothingiskeepingyouhere": "Nothing Is Keeping You Here",
        "nothingtoit": "Nothing to It",
        "n\u00e5bl\u00e5serdetp\u00e5jorden": "N\u00e5 bl\u00e5ser det p\u00e5 jorden",
        "objectsinthemirror": "Objects in the Mirror",
        "october": "October",
        "ohmyword": "Oh My Word",
        "oneinamillion": "One in a Million",
        "orangesonappletrees": "Oranges on Appletrees",
        "outofbluecomesgreen": "Out of Blue Comes Green",
        "outofthebluecomesgreen": "Out of the Blue Comes Green",
        "overthetreetops": "Over the Treetops",
        "photogallery": "Photo Gallery",
        "presentinglilymars": "Presenting Lily Mars",
        "realmeaning": "Real Meaning",
        "ridingthecrest": "Riding the Crest",
        "rollingthunder": "Rolling Thunder",
        "sailonmylove": "Sail on My Love",
        "scoundreldays": "Scoundrel Days",
        "shadowendeavors": "Shadow Endeavors",
        "shadowside": "Shadowside",
        "shapesthatgotogether": "Shapes That Go Together",
        "sheshummingatune": "She\u2019s Humming a Tune",
        "slenderframe": "Slender Frame",
        "softrainsofapril": "Soft Rains of April",
        "solace": "Solace",
        "solesurvivor": "Sole Survivor",
        "soxofthefox": "Sox of the Fox",
        "startthesimulator": "Start the Simulator",
        "stayontheseroads": "Stay on these Roads",
        "stopandmakeyourmindup": "Stop! And Make Your Mind Up",
        "summermovedon": "Summer Moved On",
        "summerrain": "Summer Rain",
        "sunalwaysshinesontv": "Sun Always Shines on T.V.",
        "sunnymystery": "Sunny Mystery",
        "swingofthings": "Swing of Things",
        "sycamoreleaves": "Sycamore Leaves",
        "s\u00e5bl\u00e5serdetp\u00e5jorden": "S\u00e5 bl\u00e5ser det p\u00e5 jorden",
        "thebandstand": "The Bandstand",
        "thebloodthatmovesthebody": "The Blood That Moves the Body",
        "thebluesky": "The Blue Sky",
        "thebreakers": "The Breakers",
        "thecompanyman": "The Company Man",
        "theendoftheaffair": "The End of the Affair",
        "thekillingmoon": "The Killing Moon",
        "thelivingdaylights": "The Living Daylights",
        "thelovegoodbye": "The Love Goodbye",
        "thesphinx": "The Sphinx",
        "thesummersofouryouth": "The Summers of Our Youth",
        "thesunalwaysshinesontv": "The Sun Always Shines on TV",
        "thesunnevershinethatday": "The Sun Never Shine That Day",
        "thesunnevershonethatday": "The Sun Never Shone That Day",
        "theswingofthings": "The Swing of Things",
        "thewake": "The Wake",
        "thewaywetalk": "The Way We Talk",
        "theweightofthewind": "The Weight of the Wind",
        "theresneveraforeverthing": "There\u2019s Never a Forever Thing",
        "theresareasonforit": "There\u2019s a Reason for It",
        "thisaloneislove": "This Alone Is Love",
        "thisisourhome": "This Is Our Home",
        "thoughtthatitwasyou": "Thought That It Was You",
        "thoughtthenitwasyou": "Thought Then It Was You",
        "thusendedourloveaffair": "Thus Ended Our Love Affair",
        "timeagain": "Time & Again",
        "timeandagain": "Time and Again",
        "toletyouwin": "To Let You Win",
        "toshowitistoblowit": "To Show It Is to Blow It",
        "touchy": "Touchy!",
        "trainofthought": "Train of Thought",
        "treeswillnotgrowonthesand": "Trees Will Not Grow on the Sand",
        "truenorth": "True North",
        "turnthelightdown": "Turn the Light Down",
        "turnthelightsdown": "Turn the Lights Down",
        "umbrella": "Umbrella",
        "underthemakeup": "Under the Makeup",
        "velvet": "Velvet",
        "waitingforher": "Waiting for Her",
        "wewillneverspeakagain": "We Will Never Speak Again",
        "werelookingforthewhales": "We\u2019re Looking for the Whales",
        "whatthereis": "What There Is",
        "whatsthatyouredoingtoyourselfinthepouringrain": "What\u2019s That You\u2019re Doing to Yourself in the Pouring Rain",
        "whitecanvas": "White Canvas",
        "whitedwarf": "White Dwarf",
        "youaretheone": "You Are the One",
        "youhavegrownthoughtfulagain": "You Have Grown Thoughtful Again",
        "youhavewhatittakes": "You Have What It Takes",
        "youwantedmore": "You Wanted More",
        "youllendupcrying": "You\u2019ll End Up Crying",
        "youllnevergetoverme": "You\u2019ll Never Get Over Me",
        "youretheone": "You're the One"
    },
    "question-a-flock-of-seagulls": {
        "cosmostheeffectofthesun": "(Cosmos) The Effect of the Sun",
        "itsnotmetalking": "It\u2019s Not Me Talking",
        "230": "2:30",
        "agelessprince": "Ageless Prince",
        "alltoyou": "All to You",
        "ascension": "Ascension",
        "betterbetter": "Better & Better",
        "burningup": "Burning Up",
        "burninup": "Burnin\u2019 Up",
        "castlesinthesky": "Castles in the Sky",
        "commited": "Commited",
        "committed": "Committed",
        "crylikeababy": "Cry Like a Baby",
        "dna": "DNA",
        "dontaskme": "Don\u2019t Ask Me",
        "dontaskmewhy": "Don\u2019t Ask Me Why",
        "electrics": "Electrics",
        "european": "European",
        "factorymusic": "Factory Music",
        "fireinthesky": "Fire in the Sky",
        "gottogettoyou": "Got to Get to You",
        "heartofsteel": "Heart of Steel",
        "heartbeatlikeadrum": "Heartbeat Like a Drum",
        "heartsonfire": "Hearts on Fire",
        "him": "Him",
        "hottonight": "Hot Tonight",
        "howcouldyoueverleaveme": "How Could You Ever Leave Me",
        "lifeiseasy": "Life Is Easy",
        "lipslikesugar": "Lips Like Sugar",
        "livinginheaven": "Living in Heaven",
        "lostcontrol": "Lost Control",
        "loveonyourknees": "Love on Your Knees",
        "loversandstrangers": "Lovers and Strangers",
        "lovesoverture": "Loves Overture",
        "magic": "Magic",
        "manmade": "Manmade",
        "messages": "Messages",
        "messagesfromtheringsofsaturn": "Messages From the Rings of Saturn",
        "modernloveisautomatic": "Modern Love Is Automatic",
        "neveragain": "Never Again",
        "nightmares": "Nightmares",
        "ordinaryman": "Ordinary Man",
        "overmyhead": "Over My Head",
        "overtheborder": "Over the Border",
        "perfect": "Perfect",
        "pickmeup": "Pick Me Up",
        "quicksand": "Quicksand",
        "rainfall": "Rainfall",
        "rememberdavid": "Remember David",
        "rosenmontag": "Rosenmontag",
        "sandy": "Sandy",
        "saysomuch": "Say So Much",
        "sayyouloveme": "Say You Love Me",
        "settingsun": "Setting Sun",
        "sevenseas": "Seven Seas",
        "somedreams": "Some Dreams",
        "spaceagelovesong": "Space Age Love Song",
        "standinginthedoorway": "Standing in the Doorway",
        "storyofayoungheart": "Story of a Young Heart",
        "suicideday": "Suicide Day",
        "talking": "Talking",
        "tanglimara": "Tanglimara",
        "telecommunication": "Telecommunication",
        "theeffectsofthesun": "The Effects Of The Sun",
        "theend": "The End",
        "thefall": "The Fall",
        "thelastflightofyurigagarin": "The Last Flight of Yuri Gagarin",
        "thelightattheendoftheworld": "The Light at the End of the World",
        "themoreyoulive": "The More You Live",
        "themoreyoulivethemoreyoulove": "The More You Live, the More You Love",
        "thestoryofayoungheart": "The Story of a Young Heart",
        "thetraveler": "The Traveler",
        "thetraveller": "The Traveller",
        "thisusedtobemyplayground": "This Used to Be My Playground",
        "tokyo": "Tokyo",
        "transferaffection": "Transfer Affection",
        "tricks": "Tricks",
        "valleyofthebrokendreams": "Valley of the Broken Dreams",
        "walkinginthegarden": "Walking in the Garden",
        "wewantitbackagain": "We Want It Back Again",
        "whatamisupposedtodo": "What Am I Supposed to Do",
        "whatyousaidwhatyoumeant": "What You Said, What You Meant",
        "wholelotofloving": "Whole Lot of Loving",
        "whosthatgirl": "Who\u2019s That Girl",
        "windows": "Windows",
        "wishin": "Wishin",
        "wishing": "Wishing",
        "wishingihadaphotographofyou": "Wishing I Had a Photograph of You",
        "wishingifihadaphotographofyou": "Wishing... If I Had a Photograph of You",
        "youcanrun": "You Can Run",
        "youreafool": "You\u2019re A Fool",
        "youremine": "You\u2019re Mine"
    },
    "question-matthew-wilder": {
        "agirlworthfightingfor": "A Girl Worth Fighting For",
        "blindfoldgift": "Blindfold Gift",
        "bouncinoffthewalls": "Bouncin\u2019 Off the Walls",
        "cryjustalittle": "Cry Just a Little",
        "diefrauf\u00fcrdieeinkampfsichlohntyaochienpomulanlingchifu": "Die Frau, F\u00fcr Die Ein Kampf Sich Lohnt - Yao, Chien-Po, Mulan, Ling,Chi Fu",
        "dreamskeepbringingyouback": "Dreams Keep Bringing You Back",
        "ehref\u00fcrdashausmulangrossmutterfa": "Ehre F\u00fcr Das Haus - Mulan, Grossmutter Fa",
        "fortunecookie": "Fortune Cookie",
        "heylittlegirl": "Hey Little Girl",
        "hombresdeacci\u00f3n": "Hombres de acci\u00f3n",
        "honortousall": "Honor to Us All",
        "honourtousall": "Honour to Us All",
        "idontspeakthelanguage": "I Don\u2019t Speak the Language",
        "iwasthere": "I Was There",
        "illmakeamanoutofyou": "I\u2019ll Make a Man Out of You",
        "lattaccodegliunni": "L'attacco degli Unni",
        "ladderoflovers": "Ladder of Lovers",
        "loveabovethegroundfloor": "Love Above the Ground Floor",
        "loveofanamazon": "Love of an Amazon",
        "madforyou": "Mad for You",
        "mulan": "Mulan",
        "mulanwerbinich": "Mulan: Wer bin ich?",
        "nakedtruth": "Naked Truth",
        "newbeginnings": "New Beginnings",
        "openup": "Open Up",
        "overture": "Overture",
        "reflection": "Reflection",
        "reflejo": "Reflejo",
        "rockpendulum": "Rock Pendulum",
        "scandal": "Scandal",
        "seieinmannlishangmulanmushuyaochienpoling": "Sei Ein Mann - Li Shang, Mulan, Mushu, Yao, Chien-Po, Ling",
        "separatehouses": "Separate Houses",
        "theargument": "The Argument",
        "thehomecoming": "The Homecoming",
        "thekidsamerican": "The Kid\u2019s American",
        "theplaydate": "The Play Date",
        "thetippingpoint": "The Tipping Point",
        "theuncertaingift": "The Uncertain Gift",
        "tightrope": "Tight Rope",
        "watchmefly": "Watch Me Fly",
        "werbinichmulan": "Wer Bin Ich? - Mulan",
        "worldoftherichandfamous": "World of the Rich and Famous"
    }
}
